//
// Generated file, do not edit! Created by opp_msgtool 6.0 from CodingRatePacket.msg.
//

#ifndef __CODINGRATEPACKET_M_H
#define __CODINGRATEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CodingRatePacket;
#include "Packet_m.h" // import Packet

// cplusplus {{
static const char *codingRateToString[7] = 
	{ "L3", "L2", "L1", "R", "H1", "H2", "H3" };
// }}

/**
 * Enum generated from <tt>CodingRatePacket.msg:11</tt> by opp_msgtool.
 * <pre>
 * enum CODING_RATE
 * {
 *     L3 = 0;
 *     L2 = 1;
 *     L1 = 2;
 *     R = 3;
 *     H1 = 4;
 *     H2 = 5;
 *     H3 = 6;
 * }
 * </pre>
 */
enum CODING_RATE {
    L3 = 0,
    L2 = 1,
    L1 = 2,
    R = 3,
    H1 = 4,
    H2 = 5,
    H3 = 6
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CODING_RATE& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CODING_RATE& e) { int n; b->unpack(n); e = static_cast<CODING_RATE>(n); }

/**
 * Class generated from <tt>CodingRatePacket.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet CodingRatePacket extends Packet
 * {
 *     CODING_RATE codingRate;
 * }
 * </pre>
 */
class CodingRatePacket : public ::Packet
{
  protected:
    CODING_RATE codingRate = static_cast<CODING_RATE>(-1);

  private:
    void copy(const CodingRatePacket& other);

  protected:
    bool operator==(const CodingRatePacket&) = delete;

  public:
    CodingRatePacket(const char *name=nullptr, short kind=0);
    CodingRatePacket(const CodingRatePacket& other);
    virtual ~CodingRatePacket();
    CodingRatePacket& operator=(const CodingRatePacket& other);
    virtual CodingRatePacket *dup() const override {return new CodingRatePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual CODING_RATE getCodingRate() const;
    virtual void setCodingRate(CODING_RATE codingRate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CodingRatePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CodingRatePacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CodingRatePacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<CodingRatePacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CODINGRATEPACKET_M_H

