//
// Generated file, do not edit! Created by opp_msgtool 6.0 from customTimer.msg.
//

#ifndef __CUSTOMTIMER_M_H
#define __CUSTOMTIMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CustomTimer;
/**
 * Class generated from <tt>customTimer.msg:3</tt> by opp_msgtool.
 * <pre>
 * message CustomTimer
 * {
 *     int terminalId;
 * }
 * </pre>
 */
class CustomTimer : public ::omnetpp::cMessage
{
  protected:
    int terminalId = 0;

  private:
    void copy(const CustomTimer& other);

  protected:
    bool operator==(const CustomTimer&) = delete;

  public:
    CustomTimer(const char *name=nullptr, short kind=0);
    CustomTimer(const CustomTimer& other);
    virtual ~CustomTimer();
    CustomTimer& operator=(const CustomTimer& other);
    virtual CustomTimer *dup() const override {return new CustomTimer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTerminalId() const;
    virtual void setTerminalId(int terminalId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomTimer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomTimer& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CustomTimer *fromAnyPtr(any_ptr ptr) { return check_and_cast<CustomTimer*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMTIMER_M_H

