//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Frame.msg.
//

#ifndef __FRAME_M_H
#define __FRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Block;
class Frame;
#include "CodingRatePacket_m.h" // import CodingRatePacket

/**
 * Class generated from <tt>Frame.msg:5</tt> by opp_msgtool.
 * <pre>
 * class Block extends cObject
 * {
 *     int maxSize;
 *     int usedSize;
 *     CODING_RATE codingRate;
 *     Packet *packets[];
 * }
 * </pre>
 */
class Block : public ::omnetpp::cObject
{
  protected:
    int maxSize = 0;
    int usedSize = 0;
    CODING_RATE codingRate = static_cast<CODING_RATE>(-1);
    Packet * *packets = nullptr;
    size_t packets_arraysize = 0;

  private:
    void copy(const Block& other);

  protected:
    bool operator==(const Block&) = delete;

  public:
    Block();
    Block(const Block& other);
    virtual ~Block();
    Block& operator=(const Block& other);
    virtual Block *dup() const override {return new Block(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMaxSize() const;
    virtual void setMaxSize(int maxSize);

    virtual int getUsedSize() const;
    virtual void setUsedSize(int usedSize);

    virtual CODING_RATE getCodingRate() const;
    virtual void setCodingRate(CODING_RATE codingRate);

    virtual void setPacketsArraySize(size_t size);
    virtual size_t getPacketsArraySize() const;
    virtual const Packet * getPackets(size_t k) const;
    virtual Packet * getPacketsForUpdate(size_t k) { return const_cast<Packet *>(const_cast<Block*>(this)->getPackets(k));}
    virtual void setPackets(size_t k, Packet * packets);
    virtual void insertPackets(size_t k, Packet * packets);
    [[deprecated]] void insertPackets(Packet * packets) {appendPackets(packets);}
    virtual void appendPackets(Packet * packets);
    virtual void erasePackets(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Block& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Block& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Frame.msg:13</tt> by opp_msgtool.
 * <pre>
 * packet Frame
 * {
 *     Block blocks[];
 * }
 * </pre>
 */
class Frame : public ::omnetpp::cPacket
{
  protected:
    Block *blocks = nullptr;
    size_t blocks_arraysize = 0;

  private:
    void copy(const Frame& other);

  protected:
    bool operator==(const Frame&) = delete;

  public:
    Frame(const char *name=nullptr, short kind=0);
    Frame(const Frame& other);
    virtual ~Frame();
    Frame& operator=(const Frame& other);
    virtual Frame *dup() const override {return new Frame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual void setBlocksArraySize(size_t size);
    virtual size_t getBlocksArraySize() const;
    virtual const Block& getBlocks(size_t k) const;
    virtual Block& getBlocksForUpdate(size_t k) { return const_cast<Block&>(const_cast<Frame*>(this)->getBlocks(k));}
    virtual void setBlocks(size_t k, const Block& blocks);
    virtual void insertBlocks(size_t k, const Block& blocks);
    [[deprecated]] void insertBlocks(const Block& blocks) {appendBlocks(blocks);}
    virtual void appendBlocks(const Block& blocks);
    virtual void eraseBlocks(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Frame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Frame& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Block *fromAnyPtr(any_ptr ptr) { return check_and_cast<Block*>(ptr.get<cObject>()); }
template<> inline Frame *fromAnyPtr(any_ptr ptr) { return check_and_cast<Frame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FRAME_M_H

