//
// Generated file, do not edit! Created by opp_msgtool 6.0 from terminalPacket.msg.
//

#ifndef __TERMINALPACKET_M_H
#define __TERMINALPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TerminalPacket;
/**
 * Class generated from <tt>terminalPacket.msg:3</tt> by opp_msgtool.
 * <pre>
 * message TerminalPacket
 * {
 *     int terminalId;
 *     int byteLength;
 * }
 * </pre>
 */
class TerminalPacket : public ::omnetpp::cMessage
{
  protected:
    int terminalId = 0;
    int byteLength = 0;

  private:
    void copy(const TerminalPacket& other);

  protected:
    bool operator==(const TerminalPacket&) = delete;

  public:
    TerminalPacket(const char *name=nullptr, short kind=0);
    TerminalPacket(const TerminalPacket& other);
    virtual ~TerminalPacket();
    TerminalPacket& operator=(const TerminalPacket& other);
    virtual TerminalPacket *dup() const override {return new TerminalPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTerminalId() const;
    virtual void setTerminalId(int terminalId);

    virtual int getByteLength() const;
    virtual void setByteLength(int byteLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TerminalPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TerminalPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TerminalPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<TerminalPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TERMINALPACKET_M_H

